### PR TITLE
Add (failing) test for filename glob

### PR DESCRIPTION
**Pull request by IanVS**
Maybe I'm using this wrong, but I would expect the test in this PR to pass.  And in fact I have this kind of situation in my storybook PR that is failing as well, which is why I figured I'd put this together and find out whether it's a bug.  

I also added jest to devDependencies, since I wasn't able to run the tests without it.

### CODE REVIEW

**Comment by thecodrr** [comment]
I tested around and this can easily be fixed by setting `basename` property to `true` in the `picomatch` matcher function. This effectively makes the glob matcher to match against base names in addition to full paths. This also allows picomatch to match against non-full paths. I think we can make it the default until #81 is merged which adds a new method that exposes the internal picomatch options.

**Comment by IanVS** [comment]
Thanks for taking a look.  I suppose for now, I can just add the `crawl` path to the start of my globs, right?

**Comment by thecodrr** [comment]
@IanVS 

After v6.0.2, this test now passes as follows:

```ts
  const api = new fdir()
    .withBasePath()
    .globWithOptions(["a.js"], { basename: true })
    .crawl("__tests__/fixtures");
  const files = await api.withPromise();
  expect(files).toEqual(["__tests__/fixtures/a.js"]);
```

or as follows:

```ts
  const api = new fdir()
    .withBasePath()
    .glob("**/a.js")
    .crawl("__tests__/fixtures");
  const files = await api.withPromise();
  expect(files).toEqual(["__tests__/fixtures/a.js"]);
```

**Comment by IanVS** [comment]
Awesome, I'll close this out then, thanks!

**Pull request closed without merging**
